/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stm32f407xx.h>
#include <gpio_driver.h>

void example_gpio_led_toggle();
void example_gpio_led_btn();
void example_gpio_led_btn_interrupt();

int main(void)
{
    // example_gpio_led_toggle();
    // example_gpio_led_btn();
    example_gpio_led_btn_interrupt();

	for (;;);
    return 0;
}

void delay() {
    for (int i = 0; i < 250000; i++);
}

// IRQ handlers

void EXTI0_IRQHandler(void) {
    gpio_toggle_output_pin(GPIOD, GPIO_PIN_NO_12);
    delay();
    gpio_irq_handling(GPIO_PIN_NO_0);
}

// Examples

void example_gpio_led_toggle_1() {
    gpio_handle_t gpio_handle = {0};
    gpio_handle.gpiox = GPIOD;
    gpio_handle.gpio_pin_config.pin_no = GPIO_PIN_NO_12;
    gpio_handle.gpio_pin_config.mode = GPIO_MODE_OUT;
    gpio_handle.gpio_pin_config.speed = GPIO_SPEED_FAST;
    gpio_handle.gpio_pin_config.op_type = GPIO_OP_TYPE_PP;
    gpio_handle.gpio_pin_config.pupd = GPIO_PIN_PUPD_NONE;

    gpio_clock_ctrl(GPIOD, STATUS_ENABLE);
    gpio_init(&gpio_handle);

    while (1) {
        gpio_toggle_output_pin(GPIOD, GPIO_PIN_NO_12);
        delay();
    }
}

void example_gpio_led_btn() {
    gpio_handle_t gpio_led_handle = {0};
    gpio_led_handle.gpiox = GPIOD;
    gpio_led_handle.gpio_pin_config.pin_no = GPIO_PIN_NO_12;
    gpio_led_handle.gpio_pin_config.mode = GPIO_MODE_OUT;
    gpio_led_handle.gpio_pin_config.speed = GPIO_SPEED_FAST;
    gpio_led_handle.gpio_pin_config.op_type = GPIO_OP_TYPE_PP;
    gpio_led_handle.gpio_pin_config.pupd = GPIO_PIN_PUPD_NONE;

    gpio_handle_t gpio_btn_handle = {0};
    gpio_btn_handle.gpiox = GPIOA;
    gpio_btn_handle.gpio_pin_config.pin_no = GPIO_PIN_NO_0;
    gpio_btn_handle.gpio_pin_config.mode = GPIO_MODE_IN;
    gpio_btn_handle.gpio_pin_config.speed = GPIO_SPEED_FAST;
    gpio_btn_handle.gpio_pin_config.op_type = GPIO_OP_TYPE_OD;
    gpio_btn_handle.gpio_pin_config.pupd = GPIO_PIN_PUPD_NONE;

    gpio_clock_ctrl(GPIOD, STATUS_ENABLE);
    gpio_clock_ctrl(GPIOA, STATUS_ENABLE);
    gpio_init(&gpio_led_handle);
    gpio_init(&gpio_btn_handle);

    while (1) {
        if (gpio_read_input_pin(GPIOA, GPIO_PIN_NO_0)) {
            gpio_write_output_pin(GPIOD, GPIO_PIN_NO_12, PIN_SET);
        } else {
            gpio_write_output_pin(GPIOD, GPIO_PIN_NO_12, PIN_RESET);
        }
        delay();
    }
}

void example_gpio_led_btn_interrupt() {
    gpio_handle_t gpio_led_handle = {0};
    gpio_led_handle.gpiox = GPIOD;
    gpio_led_handle.gpio_pin_config.pin_no = GPIO_PIN_NO_12;
    gpio_led_handle.gpio_pin_config.mode = GPIO_MODE_OUT;
    gpio_led_handle.gpio_pin_config.speed = GPIO_SPEED_FAST;
    gpio_led_handle.gpio_pin_config.op_type = GPIO_OP_TYPE_PP;
    gpio_led_handle.gpio_pin_config.pupd = GPIO_PIN_PUPD_NONE;

    gpio_handle_t gpio_btn_handle = {0};
    gpio_btn_handle.gpiox = GPIOA;
    gpio_btn_handle.gpio_pin_config.pin_no = GPIO_PIN_NO_0;
    gpio_btn_handle.gpio_pin_config.mode = GPIO_MODE_IT_FT;
    gpio_btn_handle.gpio_pin_config.speed = GPIO_SPEED_FAST;
    gpio_btn_handle.gpio_pin_config.op_type = GPIO_OP_TYPE_OD;
    gpio_btn_handle.gpio_pin_config.pupd = GPIO_PIN_PUPD_NONE;

    gpio_clock_ctrl(GPIOD, STATUS_ENABLE);
    gpio_clock_ctrl(GPIOA, STATUS_ENABLE);
    gpio_init(&gpio_led_handle);
    gpio_init(&gpio_btn_handle);

    gpio_irq_priority_config(IRQ_NO_EXTI0, NVIC_IRQ_PRIORITY_0);
    gpio_irq_interrupt_config(IRQ_NO_EXTI0, STATUS_ENABLE);

    for (;;);
}
